### PR TITLE
[Melodic]

### PR DESCRIPTION
**Pull request by benmaidel**
ref https://github.com/ipa320/care-o-bot/issues/52

superseeds https://github.com/ipa320/cob_gazebo_plugins/pull/37

I've removed the last commit from @ompugao concerning the pid interface because of @fmessmer comment https://github.com/ipa320/cob_gazebo_plugins/pull/37#pullrequestreview-267692954

This should be compatible with kinetic and melodic if the `hardware_interface` prefix is used for all transmissions.

### CODE REVIEW

**Review by fmessmer — DISMISSED** [review]
I can confirm that the plugin still works for kinetic - when using https://github.com/ipa320/cob_common/pull/271

**Review by fmessmer — DISMISSED** [review]

**Review by fmessmer — COMMENTED** [review]
I see the following warning:
```
[ WARN] [1564736237.339278403, 0.469000000]: The default_robot_hw_sim plugin is using the Joint::SetPosition method without preserving the link velocity.
[ WARN] [1564736237.339305046, 0.469000000]: As a result, gravity will not be simulated correctly for your model.
[ WARN] [1564736237.339321186, 0.469000000]: Please set gazebo_pid parameters, switch to the VelocityJointInterface or EffortJointInterface, or upgrade to Gazebo 9.
[ WARN] [1564736237.339335329, 0.469000000]: For details, see https://github.com/ros-simulation/gazebo_ros_pkgs/issues/612
```

this might not necessarily be related to this PR, but I would like to investigate before merging

**Review by floweisshardt — DISMISSED** [review]

**Comment by fmessmer** [comment]
maybe we can do something like this: https://github.com/ros-simulation/gazebo_ros_pkgs/pull/550
to be compatible with both with and without prefix

**Comment by fmessmer** [comment]
@benmaidel please re-test this branch with melodic simulation to help me verify the dual-distro compatibility...thx

**Review by fmessmer — APPROVED** [review]

**Pull request merged**
